// <auto-generated />
using System;
using ClickerGame.Upgrades.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClickerGame.Upgrades.Migrations
{
    [DbContext(typeof(UpgradesDbContext))]
    [Migration("20250815211357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClickerGame.Upgrades.Domain.Entities.PlayerUpgrade", b =>
                {
                    b.Property<Guid>("PlayerUpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpgradedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpgradeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlayerUpgradeId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PurchasedAt");

                    b.HasIndex("UpgradeId");

                    b.HasIndex("PlayerId", "UpgradeId")
                        .IsUnique();

                    b.ToTable("PlayerUpgrades");
                });

            modelBuilder.Entity("ClickerGame.Upgrades.Domain.Entities.Upgrade", b =>
                {
                    b.Property<string>("UpgradeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Effects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prerequisites")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UpgradeId");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("Rarity");

                    b.HasIndex("Category", "IsActive");

                    b.ToTable("Upgrades");
                });

            modelBuilder.Entity("ClickerGame.Upgrades.Domain.Entities.PlayerUpgrade", b =>
                {
                    b.HasOne("ClickerGame.Upgrades.Domain.Entities.Upgrade", "Upgrade")
                        .WithMany("PlayerUpgrades")
                        .HasForeignKey("UpgradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upgrade");
                });

            modelBuilder.Entity("ClickerGame.Upgrades.Domain.Entities.Upgrade", b =>
                {
                    b.Navigation("PlayerUpgrades");
                });
#pragma warning restore 612, 618
        }
    }
}
